
import type { Battery, Inverter, PredefinedEquipment } from './types';

export const PREDEFINED_EQUIPMENT: PredefinedEquipment[] = [
  { name: 'Geladeira Simples', power: 250 },
  { name: 'Geladeira Duplex', power: 500 },
  { name: 'Ar Condicionado (Pequeno)', power: 1000 },
  { name: 'TV LED', power: 150 },
  { name: 'Lâmpada LED', power: 10 },
  { name: 'Computador/Notebook', power: 200 },
  { name: 'Micro-ondas', power: 1200 },
  { name: 'Máquina de Lavar', power: 600 },
  { name: 'Ventilador', power: 100 },
  { name: 'Roteador Wi-Fi', power: 10 },
  { name: 'Carregador de Celular', power: 15 },
  { name: 'Carregador de Notebook', power: 65 },
];

// Corrente, dimensões e peso: ficha técnica Dyness DL5.0C (2024-10-11).
// https://dyness.com/Public/Uploads/uploadfile/files/20241023/DynessDL5.0CdatasheetEN.pdf
export const DYNESS_BATTERY: Battery = {
  name: 'DYNESS - DL5.0C LV',
  voltage: 51.2,
  capacityAh: 100,
  capacityKwh: 5.12,
  usefulEnergyKwh: 4.60, // Referência conservadora do portfólio, com DoD 90%
  recommendedDod: 90,
  maximumDod: 90,
  maxDischargeCurrent: 100,
  weight: 54,
  dimensions: '558 × 545 × 150 mm',
  protocol: 'RS485 / CAN',
  lifespanCycles: 6000,
  parallelUnits: 50,
  ipClass: 'IP20',
  voltageType: 'LV',
  imageUrl: '/assets/images/dyness-dl5-0c-lv.png',
};

// Dados complementares: manual Powerbox G2, versão 20240808-V1-EN.
// https://za.dyness.com/Public/Uploads/uploadfile/files/20241023/PowerBoxG2UserManualENV1.pdf
export const DYNESS_POWERBOX_G2_BATTERY: Battery = {
  name: 'DYNESS - POWERBOX G2',
  voltage: 51.2,
  capacityAh: 200,
  capacityKwh: 10.24,
  usefulEnergyKwh: 9.72, // Referência conservadora do portfólio, com DoD 95%
  recommendedDod: 95,
  maximumDod: 95,
  maxDischargeCurrent: 200,
  weight: 96,
  dimensions: '710 × 640 × 165 mm',
  protocol: 'RS485 / CAN',
  lifespanCycles: 8000,
  parallelUnits: 50,
  ipClass: 'IP65',
  voltageType: 'LV',
  imageUrl: '/assets/images/dyness-powerbox-g2.png',
};

export const DYNESS_BATTERIES: Battery[] = [DYNESS_BATTERY, DYNESS_POWERBOX_G2_BATTERY];

// Dados complementares: manual Sec Power SPLFP 48V-TE, revisão 02 (02/05/2024).
// https://cdn.bluesundobrasil.com.br/datasheets/a/3c5b6db1-7f8c-48ee-8876-d2e484531119.pdf
export const SECPOWER_BATTERY: Battery = {
  name: 'SECPOWER - SPLFP 48-100 TE',
  voltage: 48,
  capacityAh: 100,
  capacityKwh: 4.8,
  usefulEnergyKwh: 3.84,
  recommendedDod: 80,
  maximumDod: 80, // Limite adotado para dimensionamento no portfólio
  maxDischargeCurrent: 100,
  weight: 42,
  dimensions: '442 × 480 × 134,5 mm',
  protocol: 'RS485 / CAN',
  lifespanCycles: 6000,
  parallelUnits: 20,
  ipClass: 'IP20',
  voltageType: 'LV',
  imageUrl: '/assets/images/secpower-splfp-48-100-te.png',
};

export const PORTFOLIO_LV_BATTERIES: Battery[] = [...DYNESS_BATTERIES, SECPOWER_BATTERY];

export const BATTERIES_STOCK: Battery[] = [
  {
    name: 'Unipower UPLFP-48V-100Ah',
    voltage: 48,
    capacityAh: 100,
    capacityKwh: 4.8,
    usefulEnergyKwh: 3.84, // Valor de referência a 80% DoD
    maxDischargeCurrent: 100,
    weight: 40.5,
    dimensions: '440 × 440 × 140 mm',
    protocol: 'RS485 / CAN',
    lifespanCycles: 4000,
    parallelUnits: 15,
    ipClass: 'IP21',
    voltageType: 'LV',
    imageUrl: '/assets/images/bateria-uplfp48-100-02-removebg-preview.png',
  },
  {
    name: 'Deye SE-F5 (5.12 kWh)',
    voltage: 51.2,
    capacityAh: 100,
    capacityKwh: 5.12,
    usefulEnergyKwh: 4.10, // 80% DoD
    maxDischargeCurrent: 100,
    weight: 41,
    dimensions: '370 × 548 × 140 mm',
    protocol: 'CAN / RS485',
    lifespanCycles: 6000,
    parallelUnits: 32,
    ipClass: 'IP21',
    voltageType: 'LV', // Low Voltage (Compatível com monofásicos)
    imageUrl: '/assets/images/Captura-de-tela-2026-01-16-125908-removebg-preview.png',
  },
  {
    name: 'GoodWe Parede/Solo LX-A5.0-30',
    voltage: 51.2,
    capacityAh: 100,
    capacityKwh: 5.12,
    usefulEnergyKwh: 5.0, // 100% DoD
    maxDischargeCurrent: 100,
    weight: 44,
    dimensions: '442 × 133 × 520 mm',
    protocol: 'CAN',
    lifespanCycles: 6000,
    parallelUnits: 30,
    ipClass: 'IP20',
    voltageType: 'LV',
    imageUrl: '/assets/images/LynxAG3combination-32-694_ja20ji.png',
  },
  {
    name: 'Deye BOS-W (Módulo HV 5.12kWh)', // Alterado para representar o MÓDULO
    voltage: 51.2, // Tensão correta do MÓDULO
    capacityAh: 100, 
    capacityKwh: 5.12,
    usefulEnergyKwh: 4.61, // ~90% DoD
    maxDischargeCurrent: 100,
    weight: 44, // Peso aprox do módulo
    dimensions: 'Standard Rack Module',
    protocol: 'CAN / RS485',
    lifespanCycles: 6000,
    parallelUnits: 16, // Até 16 racks em paralelo
    ipClass: 'IP20',
    voltageType: 'HV', // High Voltage para Inversores 380V
    imageUrl: '/assets/images/Captura-de-tela-2026-01-16-131242-removebg-preview.png',
    // installationWarning removido conforme solicitado
    minModulesSeries: 5, // Mínimo de 5 módulos em série
    maxModulesPerRack: 16, // Máximo de 16 módulos por rack (Control Box)
  },
  ...PORTFOLIO_LV_BATTERIES,
];

export const INVERTER_STOCK: Inverter[] = [
  // --- OFF-GRID (Novo) ---
  {
    name: 'INVERSOR DEYE OFF-GRID SUN-5K (OG01LP1-EU-AM2) MONOFÁSICO 220V (2 MPPT) C/ AFCI',
    power: 5000,
    outputCurrent: 21.8,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 120,
    weight: 12.65,
    dimensions: '306 × 427.5 × 176 mm',
    gridType: 'off-grid',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164437-removebg-preview_wmnxsx.png',
  },
  {
    name: 'INVERSOR DEYE OFF-GRID SUN-6K (OG01LP1-EU-AM2) MONOFÁSICO 220V (2 MPPT) C/ AFCI',
    power: 6000,
    outputCurrent: 26.1,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 135,
    weight: 12.65,
    dimensions: '306 × 427.5 × 176 mm',
    gridType: 'off-grid',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164437-removebg-preview_wmnxsx.png',
  },
  
  // --- SPLIT PHASE (BIFÁSICO) ---
  {
    name: 'INVERSOR SOLIS HÍBRIDO 5KW (S6-EH2P-02-SV-YD-L) SPLIT PHASE 110/220V (2 MPPT)',
    power: 5000,
    outputCurrent: 21.7,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 23.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/SolisSplitPhase_pkvlpk.webp',
  },
  {
    name: 'INVERSOR SOLIS HÍBRIDO 6KW (S6-EH2P-02-SV-YD-L) SPLIT PHASE 110/220V (2 MPPT)',
    power: 6000,
    outputCurrent: 26.1,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 23.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/SolisSplitPhase_pkvlpk.webp',
  },
  {
    name: 'INVERSOR SOLIS HÍBRIDO 7.5KW (S6-EH2P-02-SV-YD-L) SPLIT PHASE 110/220V (2 MPPT)',
    power: 7500,
    outputCurrent: 32.6,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 135,
    weight: 23.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/SolisSplitPhase_pkvlpk.webp',
  },
  {
    name: 'INVERSOR SOLIS HÍBRIDO 8KW (S6-EH2P-02-SV-YD-L) SPLIT PHASE 110/220V (2 MPPT)',
    power: 8000,
    outputCurrent: 34.8,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 135,
    weight: 23.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/SolisSplitPhase_pkvlpk.webp',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-6K (SG05LP2-US-SM2) SPLIT PHASE 110/220V (2 MPPT) C/ AFCI',
    power: 6000,
    outputCurrent: 25,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65 / NEMA 3R',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 135,
    weight: 29.2,
    dimensions: '386 × 606.5 × 240 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_163937-removebg-preview_xc46lq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-7.5K (SG05LP2-US-SM2) SPLIT PHASE 110/220V (2 MPPT) C/ AFCI',
    power: 8000,
    outputCurrent: 31.5,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65 / NEMA 3R',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 190,
    weight: 29.2,
    dimensions: '386 × 606.5 × 240 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_163937-removebg-preview_xc46lq.png',
  },

  // --- MONOFÁSICOS (220V) ---
  {
    name: 'INVERSOR SOLIS HÍBRIDO 5KW (S6-EH1P-L-PLUS) MONOFÁSICO 220V (2 MPPT)',
    power: 5000,
    outputCurrent: 22.7,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 21.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Solis_Mono_pxrh4i.webp',
  },
  {
    name: 'INVERSOR SOLIS HÍBRIDO 6KW (S6-EH1P-L-PLUS) MONOFÁSICO 220V (2 MPPT)',
    power: 6000,
    outputCurrent: 27.3,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 21.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Solis_Mono_pxrh4i.webp',
  },
  {
    name: 'INVERSOR SOLIS HÍBRIDO 8KW (S6-EH1P-L-PLUS) MONOFÁSICO 220V (2 MPPT)',
    power: 8000,
    outputCurrent: 36.4,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lithium-ion / Lead-acid',
    maxChargeDischargeCurrent: 135,
    weight: 21.5,
    dimensions: '333 × 472 × 216 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Solis_Mono_pxrh4i.webp',
  },
  {
    name: 'INVERSOR SOLPLANET HÍBRIDO ASW 5KW (H-S2) MONOFÁSICO 220V',
    power: 5000,
    outputCurrent: 22.7,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'LiFePO₄ / Li-Ion',
    maxChargeDischargeCurrent: 100,
    weight: 21.5,
    dimensions: '494 × 420 × 195 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Hybrid-1.png',
  },
  {
    name: 'INVERSOR SOLPLANET HÍBRIDO ASW 6KW (H-S2) MONOFÁSICO 220V C/ AFCI',
    power: 6000,
    outputCurrent: 27.3,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'LiFePO₄ / Li-Ion',
    maxChargeDischargeCurrent: 100,
    weight: 21.5,
    dimensions: '494 × 420 × 195 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Hybrid-1.png',
  },
  {
    name: 'INVERSOR GOODWE HIBRIDO GW6KW (ES-BR20) MONOFASICO 220V (2 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 6000,
    outputCurrent: 27.3,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 120,
    weight: 21.5,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/ESLD-32.png',
  },
  {
    name: 'INVERSOR GOODWE HIBRIDO GW3.5KW (L-ES-BR20) MONOFASICO 127V (2 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 3500,
    outputCurrent: 27.5,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 75,
    weight: 21.5,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/ESG2-33.webp',
  },
  {
    name: 'INVERSOR GOODWE HIBRIDO GW3.6KW (ES-BR20) MONOFASICO 220V (2 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 3600,
    outputCurrent: 16.4,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 21.5,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/ESLD-32.png',
  },
  {
    name: 'INVERSOR GOODWE HÍBRIDO 5KW (ES-LD-G10) SPLIT PHASE 110/220V (2 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 5000,
    outputCurrent: 22.7,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 21.5,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/ESLD-32.png',
  },
  {
    name: 'INVERSOR GOODWE HÍBRIDO 7.5KW (ES-LD-G10) SPLIT PHASE 110/220V (2 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 7500,
    outputCurrent: 34.1,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 150,
    weight: 21.5,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/ESLD-32.png',
  },
  {
    name: 'INVERSOR GOODWE HÍBRIDO 10KW (ES-LD-G10) SPLIT PHASE 110/220V (2 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 10000,
    outputCurrent: 45.5,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 200,
    weight: 21.5,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'split-phase',
    imageUrl: '/assets/images/ESLD-32.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-6K (SG04LP1-EU-SM2) MONOFÁSICO 220V (2 MPPT) C/ AFCI',
    power: 6000,
    outputCurrent: 27.3,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 135,
    weight: 17.6,
    dimensions: '376 × 470 × 241.5 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164437-removebg-preview_wmnxsx.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-7.5K (SG05LP1-EU-SM2) MONOFÁSICO 220V (2 MPPT) C/ AFCI',
    power: 7500,
    outputCurrent: 34.1,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 190,
    weight: 26.8,
    dimensions: '366 × 589.5 × 237 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164437-removebg-preview_wmnxsx.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-10K (SG05LP1-EU-SM2-P) MONOFÁSICO 220V (2 MPPT) C/ AFCI',
    power: 10000,
    outputCurrent: 45.5,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 4,
    ipClass: 'IP65',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Lead-acid / Lithium-ion',
    maxChargeDischargeCurrent: 210,
    weight: 26.8,
    dimensions: '366 × 589.5 × 237 mm',
    gridType: 'monophasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164437-removebg-preview_wmnxsx.png',
  },

  // --- TRIFÁSICOS (380V) ---
  {
    name: 'INVERSOR GOODWE HIBRIDO GW12KW (ET-LL-G10) TRIFÁSICO 220V (3 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 12000,
    outputCurrent: 31.5,
    mpptEfficiency: 99.9,
    efficiency: 97.8,
    upsSwitchTime: 4,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'LFP / Lead-acid',
    maxChargeDischargeCurrent: 250,
    weight: 45.1,
    dimensions: '756 × 551 × 258 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/ETLV6-20K-32_gohbwk.png',
  },
  {
    name: 'INVERSOR GOODWE HIBRIDO GW12KW (ET-L-G10) TRIFÁSICO 380V (3 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 12000,
    outputCurrent: 18.2,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 24,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/ETLV6-20K-32_gohbwk.png',
  },
  {
    name: 'INVERSOR GOODWE HIBRIDO GW15KW (ET-L-G10) TRIFÁSICO 380V (4 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 15000,
    outputCurrent: 22.8,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 24,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/ETLV6-20K-32_gohbwk.png',
  },
  {
    name: 'INVERSOR GOODWE HIBRIDO GW20KW (ET-L-G10) TRIFÁSICO 380V (4 MPPT) c/ AFCI | BAT. LOW VOLTAGE',
    power: 20000,
    outputCurrent: 30.4,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP66',
    batteryVoltageRange: '40V - 60V',
    batteryType: 'Li-Ion / Lead-acid',
    maxChargeDischargeCurrent: 100,
    weight: 24,
    dimensions: '505.9 × 434.9 × 154.8 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/ETLV6-20K-32_gohbwk.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-12K (SG01HP3-EU-DM2) TRIFÁSICO 380V (2 MPPT) C/ AFCI',
    power: 12000,
    outputCurrent: 18.2, 
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 700V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 37,
    weight: 30.5,
    dimensions: '408 × 638 × 237 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-15K (SG01HP3-EU-AM2) TRIFÁSICO 380V (2 MPPT) C/ AFCI',
    power: 15000,
    outputCurrent: 22.8,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 700V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 37,
    weight: 30.5,
    dimensions: '408 × 638 × 237 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-20K (SG01HP3-EU-AM2) TRIFÁSICO 380V (2 MPPT) C/ AFCI',
    power: 20000,
    outputCurrent: 30.4,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 700V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 50,
    weight: 30.5,
    dimensions: '408 × 638 × 237 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-25K (SG01HP3-EU-AM2) TRIFÁSICO 380V (2 MPPT) C/ AFCI',
    power: 25000,
    outputCurrent: 38.0,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 700V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 50,
    weight: 30.5,
    dimensions: '408 × 638 × 237 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-30K (SG02HP3-EU-AM3) TRIFÁSICO 380V (3 MPPT) C/ AFCI',
    power: 30000,
    outputCurrent: 45.5,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 700V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 75,
    weight: 46,
    dimensions: '448 × 688 × 270 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-50K (SG01HP3-EU-BM4) TRIFÁSICO 380V (4 MPPT) C/ AFCI',
    power: 50000,
    outputCurrent: 75.8,
    mpptEfficiency: 99.9,
    efficiency: 97.6,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 800V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 100,
    weight: 80,
    dimensions: '527 × 894 × 294 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  },
  {
    name: 'INVERSOR DEYE HÍBRIDO SUN-75K (SG02HP3-EU-EM6) TRIFÁSICO 380V (6 MPPT) C/ AFCI',
    power: 75000,
    outputCurrent: 113.7,
    mpptEfficiency: 99.9,
    efficiency: 98.7,
    upsSwitchTime: 10,
    ipClass: 'IP65',
    batteryVoltageRange: '160V - 1000V',
    batteryType: 'Li-Ion HV',
    maxChargeDischargeCurrent: 160,
    weight: 105,
    dimensions: '606 × 927 × 314 mm',
    gridType: 'triphasic',
    imageUrl: '/assets/images/Captura_de_tela_2026-04-06_164648-removebg-preview_iemuuq.png',
  }
];
